### ISSUE TITLE
C++ Single Definition Rule

### ISSUE THREAD

**Issue by micsthepick** [90th/iniParser#1]
When including this header in multiple source files, we have a violation of the single definition rule, and thus the linker complains.

**Comment by 90th** [comment]
You arent removing the 
#ifndef INIPARSER_H ?

Also, give the new update a try. its just a quick inline hack which might help, if not I'll have to give this a deeper look.

**Comment by micsthepick** [comment]
I modified my local copy to use inline, and that seems to work, and I've reviewed the code, LGTM.
