### ISSUE TITLE
#include <algorithm> is necessary with `gcc-arm-none-eabi` (etc?)

### ISSUE THREAD

**Issue by micsthepick** [90th/iniParser#2]
I'm compiling with blocksDS/libnds, which uses the wonderful toolchain, and requires the use of <algorithm>. Perhaps this is an older spec? Not too sure why this compiler has that requirement.

**Comment by 90th** [comment]
Hmmm, im not too sure. i mainly work with visual studio 2022 MSVC.
I'll look into this issue

**Comment by 90th** [comment]
You might need to explicitly #include <algorithm> if you are working with embedded devices.

**Comment by micsthepick** [comment]
yes, the device is an embedded target.
